# Generated by Django 6.0.4 on 2026-05-02 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='lesson',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('MCX', 'MCX'), ('NFO', 'NFO'), ('BFO', 'BFO')], default='NSE', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fund_house',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='nav',
            field=models.FloatField(blank=True, help_text='Net Asset Value for MF', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='segment',
            field=models.CharField(choices=[('equity', 'Equity (Stock)'), ('futures', 'Futures'), ('ce', 'Call Option (CE)'), ('pe', 'Put Option (PE)'), ('mf', 'Mutual Fund')], default='equity', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='strike_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mistake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='core.trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
    ]
