# Generated by Django 6.0.4 on 2026-05-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_journal_id_alter_trade_id_alter_tradegroup_id_and_more'),
        ('core', '0002_broker_usersettings_trade_broker'),
    ]

    operations = [
    ]
