# Generated by Django 6.0.4 on 2026-05-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_journal_id_alter_trade_id_alter_tradegroup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.broker'),
        ),
    ]
